title: Sample Project
description: Project Overview: Project Mars is a cloud-based social-media platform that allows users to trade skills with each other. I contributed as a Test Analyst in both Manual and Automation Testing. 

theme: jekyll-theme-slate
